### ISSUE TITLE
"4 x 1" widget is actually 4 x 2

### ISSUE THREAD

**Issue by krid** [ndscor/SubMuxic#3]
The widget labeled "4 x 1" renders as a 4x2 box when placed onto the home screen.  The visible widget is ~10% taller than the Google Play Music 4x1 widget, but it takes up twice the height on the home screen.

I am using a Google Pixel 4 XL running Android 10

**Comment by ndscor** [comment]
@krid will be fixed by the next release .

**Comment by krid** [comment]
Not fixed.  With version 2.9 there are two separate 4x2 widgets and no 4x1.
