### ISSUE TITLE
The "Next Song" button at the bottom of the screen is out of place.

### ISSUE THREAD

**Issue by orlea** [ndscor/SubMuxic#5]
I bought SubMuxic because I liked its more modern design than the Dsub.
But the "next song" button is broken in appearance.
The only problem is the look of the button, and tapping it will take you to the next song.

- Android 10.
- AQUOS sense3 SH-M12(5.5inch, 1,080*2,160)
- SubMuxic VersionCode19 VersionName '2.9

The screenshot is right after installing the app, but logging in to a server like navidrome or airsonic did not fix this appearance problem.
![image](https://user-images.githubusercontent.com/12406919/91560077-2c7ba400-e974-11ea-9f5f-7dd9cbe9f7da.png)

**Comment by krid** [comment]
Renders correctly for me (Pixel 4 XL, Android 10, v2.9)

**Comment by orlea** [comment]
How about Pixel4a?

**Comment by asgardius** [comment]
I have same issue (Moto g7 Power, Android 10, v2.9)
![Screenshot_20200904-124638381](https://user-images.githubusercontent.com/43385234/92280398-23c42a00-eeae-11ea-947a-63ace15a6016.jpg)

**Comment by asgardius** [comment]
On my Galaxy a3 2015 with Android 7 this issue is also present

**Comment by orlea** [comment]
Thanks for the update v3.0.
But it's not fixed on my device.

![be921fbc43de0212](https://user-images.githubusercontent.com/12406919/93306900-676a4c80-f83b-11ea-932c-cb8424e71a55.png)

**Comment by orlea** [comment]
This has been fixed in v3.1.
Thanks for the great work !
